version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/devops-lab2-backend:latest
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb+srv://salahboughanmi:qzEO7iQxG64B6NOY@devo.danpz.mongodb.net/?retryWrites=true&w=majority&appName=devo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3001
    image: ${DOCKER_USERNAME}/devops-lab2-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:5000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
