name: Continuous Deployment (Feature to Dev) Workflow

on:
  push:
    branches:
      - dev

jobs:
  feature_to_dev:
    name: Merge dev to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm install

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install

      - name: Run unit tests for frontend
        working-directory: ./frontend
        run: npm test

      - name: Run unit tests for backend
        working-directory: ./backend
        run: npm test

      - name: Merge dev into main
        uses: devmasx/merge-branch@master
        with:
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.TOKEN }}
          type: now